// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:b7d7fcb4-6535-4e12-b295-7ce7e19106ba",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_A6hIZ6jIK",
    "aws_user_pools_web_client_id": "7lu3rk9hgn7objg6l65a49qi6f",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ie4x7fdn7jc6xeoit6opdcmvbi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "janga-bucket-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "https://d1468qg6iabhek.cloudfront.net"
};


export default awsmobile;
